"""Acceptance Gate Tests for Phase D Recurrent SE(3) Structural Workspace Thinker.

Verifies the 6 mandatory Phase-D acceptance criteria:
  1. SO(3) Manifold Guarantee:
     Rotations generated by so3_exp_map strictly satisfy R^T R = I and det(R) = +1.
  2. Extended Linear Chain Initialization:
     Chain begins at t_i^{(0)} = (3.8 · i, 0, 0) and R_i^{(0)} = I with consecutive Cα spacing = 3.8Å.
  3. Weight-Tied Parameter Identity:
     A single shared block F_θ is applied across all recurrent steps (F_1 ≡ F_2 ≡ ... ≡ F_R).
  4. Sequence Padding Invariance:
     Padding does not leak into valid residue coordinates.
  5. Compact Parameter Footprint:
     The entire workspace thinker is lightweight (< 500k parameters).
  6. Test-Time Compute Scaling:
     Model trained on R=4 can be evaluated dynamically at R ∈ {1, 2, 4, 8} without geometric explosion.
"""

from __future__ import annotations

import pytest
import torch

from nanofold.models.geometry_se3 import (
    RigidFrames,
    make_extended_linear_chain,
    so3_exp_map,
)
from nanofold.models.workspace_thinker import (
    RecurrentWorkspaceThinker,
    WorkspaceThinkerConfig,
)

# =============================================================================
# Fixtures
# =============================================================================

@pytest.fixture
def synthetic_thinker_inputs():
    """Generates synthetic representations mimicking Phase A + Phase C outputs."""
    torch.manual_seed(42)
    B, L = 2, 24
    d_single = 128
    d_pair = 64
    d_tok = 64
    k_tokens = 16

    s = torch.randn((B, L, d_single))
    z = torch.randn((B, L, L, d_pair))
    z = 0.5 * (z + z.transpose(1, 2))  # Symmetrize
    q_tokens = torch.randn((B, k_tokens, d_tok))

    mask = torch.ones((B, L), dtype=torch.bool)
    mask[:, -4:] = False  # Last 4 residues padded

    return {
        "s": s,
        "z": z,
        "q_tokens": q_tokens,
        "mask": mask,
        "B": B,
        "L": L,
    }


# =============================================================================
# Gate 1: SO(3) Manifold Guarantee
# =============================================================================

def test_so3_manifold_guarantee():
    """Gate 1: Verify so3_exp_map strictly produces valid rotation matrices R in SO(3)."""
    torch.manual_seed(123)

    # Test random tangent vectors covering small, typical, and large rotations
    omegas = [
        torch.zeros(5, 3),                        # Identity rotation (0 rad)
        torch.randn(10, 3) * 1e-6,                # Extremely small angles (< 1e-4 rad)
        torch.randn(20, 3) * 0.5,                 # Moderate angles
        torch.randn(20, 3) * 3.1415,              # Large angles (~pi rad)
    ]

    for omega in omegas:
        R = so3_exp_map(omega)
        batch_size = omega.shape[0]

        # 1. Orthonormality: R^T · R = I
        eye = torch.eye(3, dtype=omega.dtype, device=omega.device).unsqueeze(0).expand(batch_size, -1, -1)
        r_rt = torch.matmul(R, R.transpose(-1, -2))
        ortho_diff = (r_rt - eye).abs().max().item()
        assert ortho_diff < 1e-4, f"SO(3) orthonormality violated: max diff = {ortho_diff:.6e}"

        # 2. Proper rotation: det(R) = +1
        det = torch.linalg.det(R)
        det_diff = (det - 1.0).abs().max().item()
        assert det_diff < 1e-4, f"SO(3) determinant ≠ +1: max diff = {det_diff:.6e}"


# =============================================================================
# Gate 2: Extended Linear Chain Initialization
# =============================================================================

def test_extended_linear_chain_initialization():
    """Gate 2: Verify non-degenerate extended polypeptide initialization (3.8Å spacing)."""
    B, L = 3, 20
    frames = make_extended_linear_chain(batch_size=B, seq_len=L, bond_length=3.8)

    # 1. Verify rotation is Identity
    eye = torch.eye(3).unsqueeze(0).unsqueeze(0).expand(B, L, -1, -1)
    assert torch.allclose(frames.rot, eye), "Initial rotations must be identity matrices"

    # 2. Verify Cα spacing along x-axis
    for i in range(L - 1):
        delta = frames.trans[:, i + 1, :] - frames.trans[:, i, :]
        dist = torch.norm(delta, dim=-1)
        assert torch.allclose(dist, torch.tensor([3.8] * B), atol=1e-5), (
            f"Consecutive Cα spacing at residue {i} is not 3.8Å: {dist}"
        )
        assert torch.allclose(delta[:, 1:], torch.zeros(B, 2), atol=1e-5), (
            "Extended chain must align purely along x-axis at step 0"
        )


# =============================================================================
# Gate 3: Weight-Tied Parameter Identity
# =============================================================================

def test_weight_tied_parameter_identity():
    """Gate 3: Verify F_1 ≡ F_2 ≡ ... ≡ F_R: exactly ONE reasoning block is reused."""
    cfg = WorkspaceThinkerConfig(num_steps=4)
    thinker = RecurrentWorkspaceThinker(cfg)

    # Confirm there is only ONE reasoning_block instance, not a ModuleList
    assert hasattr(thinker, "reasoning_block")
    assert not isinstance(thinker.reasoning_block, torch.nn.ModuleList)
    assert not isinstance(thinker.reasoning_block, torch.nn.Sequential)


# =============================================================================
# Gate 4: Sequence Padding Invariance
# =============================================================================

def test_workspace_padding_invariance():
    """Gate 4: Padding elements do not leak into valid residue coordinates."""
    torch.manual_seed(99)
    L_true = 16
    L_pad = 32
    d_single, d_pair, d_tok = 128, 64, 64

    s_short = torch.randn(1, L_true, d_single)
    z_short = torch.randn(1, L_true, L_true, d_pair)
    q_tokens = torch.randn(1, 16, d_tok)
    mask_short = torch.ones(1, L_true, dtype=torch.bool)

    s_pad = torch.zeros(1, L_pad, d_single)
    s_pad[:, :L_true, :] = s_short

    z_pad = torch.zeros(1, L_pad, L_pad, d_pair)
    z_pad[:, :L_true, :L_true, :] = z_short

    mask_pad = torch.zeros(1, L_pad, dtype=torch.bool)
    mask_pad[:, :L_true] = True

    cfg = WorkspaceThinkerConfig(d_h=128, d_single=d_single, d_pair=d_pair, d_tok=d_tok, num_steps=2)
    thinker = RecurrentWorkspaceThinker(cfg)
    thinker.eval()

    with torch.no_grad():
        out_short = thinker(s_short, z_short, q_tokens, mask=mask_short)
        out_pad = thinker(s_pad, z_pad, q_tokens, mask=mask_pad)

    trans_short = out_short["final_frames"].trans[:, :L_true, :]
    trans_pad = out_pad["final_frames"].trans[:, :L_true, :]

    diff = (trans_short - trans_pad).abs().max().item()
    print(f"\nMax translation difference under sequence padding: {diff:.6e} Å")
    assert diff < 1e-4, f"Padding leaked into structural coordinates: diff = {diff}"


# =============================================================================
# Gate 5: Compact Parameter Budget
# =============================================================================

def test_workspace_parameter_budget():
    """Gate 5: Verify RecurrentWorkspaceThinker is compact (< 500k params)."""
    cfg = WorkspaceThinkerConfig(d_h=128, d_single=128, d_pair=64, d_tok=64)
    thinker = RecurrentWorkspaceThinker(cfg)

    total_params = sum(p.numel() for p in thinker.parameters() if p.requires_grad)
    print(f"\nTotal RecurrentWorkspaceThinker parameters: {total_params:,}")

    assert total_params < 500_000, f"Thinker has {total_params:,} parameters, exceeding 500k budget!"


# =============================================================================
# Gate 6: Multi-Step Supervision and Test-Time Compute Scaling
# =============================================================================

def test_test_time_compute_scaling(synthetic_thinker_inputs):
    """Gate 6: Verify model can execute dynamically at R ∈ {1, 2, 4, 8} without geometric explosion."""
    cfg = WorkspaceThinkerConfig(
        d_h=128,
        d_single=128,
        d_pair=64,
        d_tok=64,
        num_steps=4,
    )
    thinker = RecurrentWorkspaceThinker(cfg)

    s = synthetic_thinker_inputs["s"]
    z = synthetic_thinker_inputs["z"]
    q_tokens = synthetic_thinker_inputs["q_tokens"]
    mask = synthetic_thinker_inputs["mask"]

    # Target frames (mock native structure)
    target_frames = RigidFrames(
        rot=torch.eye(3).unsqueeze(0).unsqueeze(0).expand(2, 24, -1, -1),
        trans=torch.randn(2, 24, 3) * 5.0,
    )

    # 1. Forward pass with default R = 4
    out_default = thinker(s, z, q_tokens, mask=mask)
    assert len(out_default["trajectory"]) == 4

    # Compute multi-step FAPE loss
    loss_dict = thinker.compute_loss(out_default["trajectory"], target_frames, mask)
    loss = loss_dict["loss"]
    loss.backward()

    # Verify gradients reach shared reasoning block
    assert thinker.reasoning_block.head_dt.weight.grad is not None
    assert torch.isfinite(thinker.reasoning_block.head_dt.weight.grad).all()
    assert thinker.reasoning_block.head_domega.weight.grad is not None
    assert torch.isfinite(thinker.reasoning_block.head_domega.weight.grad).all()

    # 2. Test-time compute scaling: run with R = 1, 2, 4, 8
    thinker.eval()
    with torch.no_grad():
        for r_steps in [1, 2, 4, 8]:
            out_r = thinker(s, z, q_tokens, mask=mask, eval_steps=r_steps)
            assert len(out_r["trajectory"]) == r_steps

            final_trans = out_r["final_frames"].trans
            final_rot = out_r["final_frames"].rot

            # Verify no NaN or explosion
            assert not torch.isnan(final_trans).any(), f"NaN in translations at R={r_steps}"
            assert not torch.isnan(final_rot).any(), f"NaN in rotations at R={r_steps}"
            assert final_trans.abs().max() < 1000.0, f"Geometric explosion detected at R={r_steps}"


def test_so3_exp_map_gradient_numerical_stability():
    """Verify so3_exp_map backward gradients remain strictly finite across dtypes and input ranges.

    Prevents non-finite gradient regressions when training under mixed precision (AMP float16/bfloat16).
    """
    test_cases = [
        ("zeros", torch.zeros(2, 8, 3)),
        ("tiny_1e-8", torch.full((2, 8, 3), 1e-8)),
        ("small_1e-6", torch.full((2, 8, 3), 1e-6)),
        ("small_1e-5", torch.full((2, 8, 3), 1e-5)),
        ("small_1e-4", torch.full((2, 8, 3), 1e-4)),
        ("moderate_0.5", torch.randn(2, 8, 3) * 0.5),
        ("pi", torch.full((2, 8, 3), 3.14159265)),
        ("large_5", torch.randn(2, 8, 3) * 5.0),
    ]

    for name, tensor_val in test_cases:
        for dtype in [torch.float32, torch.float16, torch.bfloat16]:
            omega = tensor_val.clone().to(dtype).requires_grad_(True)
            rot = so3_exp_map(omega)
            loss = rot.sum()
            loss.backward()

            assert omega.grad is not None, f"Gradient is None for {name} ({dtype})"
            assert torch.isfinite(omega.grad).all(), (
                f"Non-finite gradient in so3_exp_map for {name} ({dtype}): {omega.grad}"
            )

